id: IB898FA88
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:17:44+00:00'
last_modified: '2022-06-08T12:50:31.471237+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25300
  title: སྒྲ་བསྒྱུར་མར་པ་ལོ་ཙཱའི་རྣམ་ཐར་ཆེན་མོ་མཐོང་བ་དོན་ཡོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    32C4:
      image_group_id: I1KG25302
      title: ''
      total_pages: 284
      order: 1
      base_file: 32C4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
